server.port: 8880

solon.app:
  name: 'milvus-plus-solon'
  group: 'milvus'


milvus:
  uri: https://in03-a5357975ab80da7.api.gcp-us-west1.zillizcloud.com
  token: xxxx
  enable: true
  packages:
    - org.dromara.solon.test.model